version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      development-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: '@xterm/xterm'
      - dependency-name: '@xterm/addon-fit'
      - dependency-name: '@eslint/js'
        update-types: ['version-update:semver-major']
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major']
      - dependency-name: eslint
        update-types: ['version-update:semver-major']
      - dependency-name: typescript
        update-types: ['version-update:semver-major']
      - dependency-name: vitest
        update-types: ['version-update:semver-major']
